### ISSUE TITLE
reset password screen-1

### ISSUE THREAD

**Issue by iyiola-dev** [hngi/mobileforce-medbuzz#54]
implemented as it was in the design.
It is the design with the reset button.
@Revelationjay

**Comment by cs-onah** [comment]
Aiit... Acknowledged

**Comment by cs-onah** [comment]
Do i go on to design other screens for password reset?

**Comment by iyiola-dev** [comment]
No only your 1 screen

**Comment by iyiola-dev** [comment]
Other screens have been assigned to people

**Comment by cs-onah** [comment]
Aiit

**Comment by Fejiro001** [comment]
This issue has been tested and merged.
