### ISSUE TITLE
view single fitness reminder screen

### ISSUE THREAD

**Issue by Fejiro001** [hngi/mobileforce-medbuzz#81]
The user will be able to view a single fitness reminder, delete it and edit it
Implement designs from designers work
@ayshabintmahmud

**Comment by ayshabintmahmud** [comment]
Implemented designs from designers' work:
<img width="319" alt="single reminder page" src="https://user-images.githubusercontent.com/40881194/86023485-a4d0f200-ba23-11ea-8378-c881faf6d1b1.png">

Enabled the delete button for the user to be able to view the single fitness reminder page, and delete it and ask confirmation for delete.

<img width="297" alt="delete confirmation" src="https://user-images.githubusercontent.com/40881194/86023498-aac6d300-ba23-11ea-9e06-fdc96a86403c.png">

<img width="321" alt="Delete successful" src="https://user-images.githubusercontent.com/40881194/86023648-d649bd80-ba23-11ea-91ca-92013a283a5d.png">

**Comment by iyiola-dev** [comment]
merged and reviewed
